// src/app/layout.tsx

import QueryProvider from "@/components/query-provider"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  )
}
